### PR TITLE
support d3 v4

### PR DESCRIPTION
**Pull request by microdou**
`d3act` now supports `d3 v4`.
It is not backward compatible, so I suggest a version bump to `4.0.0`.

### CODE REVIEW

**Comment by microdou** [comment]
Oops, it is largely similar to the PR from @cdotta :)

**Comment by cdotta** [comment]
Yes! but many weeks without news :(
I think I will maintain it on my fork

**Comment by AnSavvides** [comment]
Apologies, I was away getting married :) I will have a look in the next couple of days!

**Comment by AnSavvides** [comment]
@microdou since @cdotta opened his pull request first, I am going to review & eventually merge that one if that's okay with you. Thank you so much for taking the time to do this though, I really appreciate that.

**Pull request closed without merging**
